/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccialexmaze;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bux
 */
public class JTest extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JTest.class.getName());

    /**
     * Creates new form JTest
     */
    public JTest() {
        initComponents();
        this.setName("TESTGENERAZIONELABIRINTO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabella = new javax.swing.JTable();
        btnGenera = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1049, 753));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabella.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabella.setPreferredSize(new java.awt.Dimension(620, 620));
        jScrollPane1.setViewportView(tabella);

        btnGenera.setText("Genera");
        btnGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneraActionPerformed(evt);
            }
        });

        jButton2.setText("Muovi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(btnGenera))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnGenera)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneraActionPerformed
                                       
       
        int[][] matriceInteri = l.getMappa();
        
        int righe = matriceInteri.length;
        int colonne = matriceInteri[0].length;
        
        Integer[][] dati = new Integer[righe][colonne];
        String[] intestazioni = new String[colonne];
        
        // 1. Convertiamo i dati
        for (int i = 0; i < righe; i++) {
            for (int j = 0; j < colonne; j++) {
                dati[i][j] = matriceInteri[i][j];
                intestazioni[j] = ""; // Intestazione vuota
            }
        }
        
        // 2. CREIAMO E ASSEGNIAMO IL MODELLO (Questo mancava!)
        DefaultTableModel model = new DefaultTableModel(dati, intestazioni) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evita che l'utente possa scrivere nelle celle
            }
        };
        tabella.setModel(model);
        
        // 3. Impostiamo il Renderer (i colori)
        tabella.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {
                
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                setText(""); // Nascondiamo i numeri
                
                if (value instanceof Integer) {
                    int val = (Integer) value;
                    switch (val) {
                        case 1: 
                            c.setBackground(Color.BLACK); 
                            break;
                        case 2: 
                            c.setBackground(Color.GREEN); 
                            break;
                        case 3:
                            c.setBackground(Color.RED);
                            break;
                        case 4:
                            c.setBackground(Color.YELLOW);
                            break;
                        case 5:
                            c.setBackground(Color.ORANGE);
                            break;
                        default:
                            c.setBackground(Color.WHITE); 
                            break;
                    }
                }
                return c;
            }
        });
        
        // 4. RENDIAMO LE CELLE QUADRATE (Fondamentale per l'aspetto)
        int size = 20; // Grandezza in pixel
        tabella.setRowHeight(size);
        
        for (int i = 0; i < colonne; i++) {
            tabella.getColumnModel().getColumn(i).setPreferredWidth(size);
            tabella.getColumnModel().getColumn(i).setMinWidth(size);
            tabella.getColumnModel().getColumn(i).setMaxWidth(size);
        }
        
        // Rimuoviamo la griglia grigia di default
        tabella.setShowGrid(false);
        tabella.setIntercellSpacing(new Dimension(0, 0));
        
       
    }//GEN-LAST:event_btnGeneraActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                            
    // 1. Esegue UN SOLO passo logico
    p.muovi(l);

    // 2. Sincronizza la grafica con la matrice aggiornata
    // Recuperiamo il modello e la mappa corrente
    DefaultTableModel model = (DefaultTableModel) tabella.getModel();
    int[][] mappaCorrente = l.getMappa();
    
    // Aggiorniamo il modello della tabella cella per cella
    for (int i = 0; i < mappaCorrente.length; i++) {
        for (int j = 0; j < mappaCorrente[i].length; j++) {
            model.setValueAt(mappaCorrente[i][j], i, j);
        }
    }
    
    // 3. Controlla se con questo passo il giocatore ha vinto
    if (p.terminato(l)) {
        // Opzionale: disabilita il tasto così non si può più cliccare
        jButton2.setEnabled(false); 
        javax.swing.JOptionPane.showMessageDialog(this, "Hai raggiunto l'uscita!");
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JTest().setVisible(true));
        
    }

    Labirinto l = new Labirinto();
    Player p = new Player("franco");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenera;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabella;
    // End of variables declaration//GEN-END:variables
}
